# BLOCK 1 — Writing and Calling Functions (Python equivalent)
# Lecture 3: MATLAB Summer Prep | NSBV BC2001
# -----------------------------------------------
# Python parallel: compare with block1_functions.m
# Key difference: Python functions are defined BEFORE they are called
# (opposite convention to MATLAB local functions)

import numpy as np
import matplotlib.pyplot as plt

# --- 1. Calling built-in/library functions (review) ---
x = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Mean:   ", np.mean(x))
print("Max:    ", np.max(x))
print("Std dev:", np.std(x))

# --- 2. Writing your own function ---
# In Python, functions are defined with 'def' BEFORE use
def make_sine(t, freq, amplitude):
    """
    Generate a sine wave.
    Parameters:
        t         : time vector (numpy array, seconds)
        freq      : frequency in Hz
        amplitude : peak amplitude
    Returns:
        y : sine wave (numpy array)
    """
    return amplitude * np.sin(2 * np.pi * freq * t)

t      = np.linspace(0, 1, 1000)
signal = make_sine(t, 10, 1.0)   # 10 Hz, amplitude 1.0

plt.figure()
plt.plot(t, signal, 'b-', linewidth=1.5)
plt.xlabel('Time (s)'); plt.ylabel('Amplitude')
plt.title('Sine wave generated by custom function')
plt.show()

# --- 3. Function with multiple return values ---
# Python returns a tuple; MATLAB uses [a, b] = func()
def find_peak(signal):
    """Return peak value and its index."""
    peak_idx = np.argmax(signal)    # MATLAB: [~, idx] = max(signal)
    peak_val = signal[peak_idx]
    return peak_val, peak_idx       # returns a tuple

pk, pk_idx = find_peak(signal)
print(f"\nPeak value: {pk:.4f} at index {pk_idx} (time = {t[pk_idx]:.4f} s)")

# --- 4. Calling a function in a loop across multiple frequencies ---
freqs = [4, 8, 12, 30]   # theta, alpha, beta bands

fig, axes = plt.subplots(len(freqs), 1, figsize=(10, 8))

for k, freq in enumerate(freqs):         # enumerate gives index + value
    sig_k = make_sine(t, freq, 1.0)
    axes[k].plot(t, sig_k, linewidth=1.2)
    axes[k].set_ylabel('Amp')
    axes[k].set_title(f'{freq} Hz')

axes[-1].set_xlabel('Time (s)')
fig.suptitle('EEG-like Frequency Bands')  # equivalent to sgtitle in MATLAB
plt.tight_layout()
plt.show()
