%% BLOCK 1 — Writing and Calling Functions
% Lecture 3: MATLAB Summer Prep | NSBV BC2001
% -----------------------------------------------
% So far we have written scripts (top-to-bottom commands).
% Functions let us package reusable logic with inputs and outputs.
% This is essential for neuroscience analysis — e.g. applying the
% same processing pipeline to many EEG channels or trials.

clc; clearvars;

%% 1. Calling a built-in function (review)
x = [3 1 4 1 5 9 2 6];
disp('Mean:');   disp(mean(x));
disp('Max:');    disp(max(x));
disp('Std dev:'); disp(std(x));

%% 2. Writing your own function (defined at the bottom of this file)
% Functions must be defined AFTER the main script body (or in a separate .m file)

t      = linspace(0, 1, 1000);
signal = make_sine(t, 10, 1.0);   % call our custom function: 10 Hz, amplitude 1.0

figure;
plot(t, signal, 'b-', 'LineWidth', 1.5);
xlabel('Time (s)'); ylabel('Amplitude');
title('Sine wave generated by custom function');

%% 3. Function with multiple outputs
[pk, pk_idx] = find_peak(signal);
fprintf('Peak value: %.4f at index %d (time = %.4f s)\n', pk, pk_idx, t(pk_idx));

%% 4. Calling the function in a loop across multiple frequencies
freqs = [4, 8, 12, 30];   % typical EEG frequency bands: theta, alpha, beta

figure;
for k = 1:length(freqs)
    sig_k = make_sine(t, freqs(k), 1.0);
    subplot(length(freqs), 1, k);
    plot(t, sig_k, 'LineWidth', 1.2);
    ylabel('Amp');
    title(sprintf('%d Hz', freqs(k)));
end
xlabel('Time (s)');
sgtitle('EEG-like Frequency Bands');   % super-title across all subplots

% -----------------------------------------------
% LOCAL FUNCTION DEFINITIONS (must come after main code)
% -----------------------------------------------

function y = make_sine(t, freq, amplitude)
    % make_sine  Generate a sine wave
    %   t         : time vector (seconds)
    %   freq      : frequency in Hz
    %   amplitude : peak amplitude
    %   y         : output sine wave
    y = amplitude * sin(2 * pi * freq * t);
end

function [peak_val, peak_idx] = find_peak(signal)
    % find_peak  Return the maximum value and its index
    [peak_val, peak_idx] = max(signal);
end
